// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_XJXhYmfDVhPraP0Epe2RGs3UYaCJCE',
    appId: '1:1018967995520:web:3700de063344629078e265',
    messagingSenderId: '1018967995520',
    projectId: 'teylourpetcare',
    authDomain: 'teylourpetcare.firebaseapp.com',
    storageBucket: 'teylourpetcare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxGGFszW1ch2AjGbP9e3Qk4JU-bUiduc',
    appId: '1:1018967995520:android:bce05d925c3ceb9778e265',
    messagingSenderId: '1018967995520',
    projectId: 'teylourpetcare',
    storageBucket: 'teylourpetcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8XKH58xyDBKqq58ox6TkpoTmckYWHuY',
    appId: '1:1018967995520:ios:d1828de266b0b44e78e265',
    messagingSenderId: '1018967995520',
    projectId: 'teylourpetcare',
    storageBucket: 'teylourpetcare.appspot.com',
    iosClientId: '1018967995520-dhqvj995la2vdmh4tcp5h9g2ieo3pvvn.apps.googleusercontent.com',
    iosBundleId: 'com.mdgsdc.petcare',
  );
}
